-- MySQL Script generated by MySQL Workbench
-- Tue Jan  7 10:29:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema construtora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema construtora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `construtora` DEFAULT CHARACTER SET utf8 ;
USE `construtora` ;

-- -----------------------------------------------------
-- Table `construtora`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `papel` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construtora`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(100) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `construtora`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construtora`.`construtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`construtor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoServico` TEXT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_construtor_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_construtor_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `construtora`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construtora`.`engenheiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`engenheiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `crea` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_engenheiro_usuario_idx` (`usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `crea_UNIQUE` (`crea` ASC) VISIBLE,
  CONSTRAINT `fk_engenheiro_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `construtora`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construtora`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(100) NOT NULL,
  `usuario_id` INT NOT NULL,
  `construtor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_funcionario_construtor1_idx` (`construtor_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `construtora`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_funcionario_construtor1`
    FOREIGN KEY (`construtor_id`)
    REFERENCES `construtora`.`construtor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `construtora`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(100) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_administrador_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `construtora`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construtora`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`obra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco` TEXT NOT NULL,
  `tipoObra` VARCHAR(100) NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  `cliente_id` INT NOT NULL, 
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cliente_obra` FOREIGN KEY (`cliente_id`) REFERENCES `construtora`.`cliente`(`id`)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construtora`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NOT NULL,
  `valor` FLOAT NOT NULL,
  `obra_id` INT NOT NULL,
  `engenheiro_id` INT NOT NULL,
  `construtor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contrato_obra1_idx` (`obra_id` ASC) VISIBLE,
  INDEX `fk_contrato_engenheiro1_idx` (`engenheiro_id` ASC) VISIBLE,
  INDEX `fk_contrato_construtor1_idx` (`construtor_id` ASC) VISIBLE,
  CONSTRAINT `fk_contrato_obra1`
    FOREIGN KEY (`obra_id`)
    REFERENCES `construtora`.`obra` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contrato_engenheiro1`
    FOREIGN KEY (`engenheiro_id`)
    REFERENCES `construtora`.`engenheiro` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contrato_construtor1`
    FOREIGN KEY (`construtor_id`)
    REFERENCES `construtora`.`construtor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construtora`.`transferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`transferencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `data` DATE NOT NULL,
  `administrador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transferencia_administrador1_idx` (`administrador_id` ASC) VISIBLE,
  CONSTRAINT `fk_transferencia_administrador1`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `construtora`.`administrador` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construtora`.`recebimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`recebimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transferencia_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recebimento_transferencia1_idx` (`transferencia_id` ASC) VISIBLE,
  INDEX `fk_recebimento_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_recebimento_transferencia1`
    FOREIGN KEY (`transferencia_id`)
    REFERENCES `construtora`.`transferencia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recebimento_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `construtora`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construtora`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transferencia_id` INT NOT NULL,
  `construtor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamento_transferencia1_idx` (`transferencia_id` ASC) VISIBLE,
  INDEX `fk_pagamento_construtor1_idx` (`construtor_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_transferencia1`
    FOREIGN KEY (`transferencia_id`)
    REFERENCES `construtora`.`transferencia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pagamento_construtor1`
    FOREIGN KEY (`construtor_id`)
    REFERENCES `construtora`.`construtor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
